// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package utils

// TODO(adonovan):
// - test use of explicit hasher across two maps.
// - test hashcodes are consistent with equals for a range of types
//   (e.g. all types generated by type-checking some body of real code).

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"strings"
	"sync"
	"testing"

	"golang.org/x/tools/go/types/typeutil"
)

var (
	tStr      = types.Typ[types.String]             // string
	tPStr1    = types.NewPointer(tStr)              // *string
	tPStr2    = types.NewPointer(tStr)              // *string, again
	tInt      = types.Typ[types.Int]                // int
	tChanInt1 = types.NewChan(types.RecvOnly, tInt) // <-chan int
	tChanInt2 = types.NewChan(types.RecvOnly, tInt) // <-chan int, again
)

func checkEqualButNotIdentical(t *testing.T, x, y types.Type, comment string) {
	if !types.Identical(x, y) {
		t.Errorf("%s: not equal: %s, %s", comment, x, y)
	}
	if x == y {
		t.Errorf("%s: identical: %v, %v", comment, x, y)
	}
}

func TestAxioms(t *testing.T) {
	checkEqualButNotIdentical(t, tPStr1, tPStr2, "tPstr{1,2}")
	checkEqualButNotIdentical(t, tChanInt1, tChanInt2, "tChanInt{1,2}")
}

func TestMap(t *testing.T) {
	var tmap *typeutil.Map

	// All methods but Set are safe on (*T)(nil).
	tmap.Len()
	tmap.At(tPStr1)
	tmap.Delete(tPStr1)
	tmap.KeysString()
	_ = tmap.String()

	tmap = new(typeutil.Map)

	// Length of empty map.
	if l := tmap.Len(); l != 0 {
		t.Errorf("Len() on empty Map: got %d, want 0", l)
	}
	// At of missing key.
	if v := tmap.At(tPStr1); v != nil {
		t.Errorf("At() on empty Map: got %v, want nil", v)
	}
	// Deletion of missing key.
	if tmap.Delete(tPStr1) {
		t.Errorf("Delete() on empty Map: got true, want false")
	}
	// Set of new key.
	if prev := tmap.Set(tPStr1, "*string"); prev != nil {
		t.Errorf("Set() on empty Map returned non-nil previous value %s", prev)
	}

	// Now: {*string: "*string"}

	// Length of non-empty map.
	if l := tmap.Len(); l != 1 {
		t.Errorf("Len(): got %d, want 1", l)
	}
	// At via insertion key.
	if v := tmap.At(tPStr1); v != "*string" {
		t.Errorf("At(): got %q, want \"*string\"", v)
	}
	// At via equal key.
	if v := tmap.At(tPStr2); v != "*string" {
		t.Errorf("At(): got %q, want \"*string\"", v)
	}
	// Iteration over sole entry.
	tmap.Iterate(func(key types.Type, value any) {
		if key != tPStr1 {
			t.Errorf("Iterate: key: got %s, want %s", key, tPStr1)
		}
		if want := "*string"; value != want {
			t.Errorf("Iterate: value: got %s, want %s", value, want)
		}
	})

	// Setion with key equal to present one.
	if prev := tmap.Set(tPStr2, "*string again"); prev != "*string" {
		t.Errorf("Set() previous value: got %s, want \"*string\"", prev)
	}

	// Setion of another association.
	if prev := tmap.Set(tChanInt1, "<-chan int"); prev != nil {
		t.Errorf("Set() previous value: got %s, want nil", prev)
	}

	// Now: {*string: "*string again", <-chan int: "<-chan int"}

	want1 := "{*string: \"*string again\", <-chan int: \"<-chan int\"}"
	want2 := "{<-chan int: \"<-chan int\", *string: \"*string again\"}"
	if s := tmap.String(); s != want1 && s != want2 {
		t.Errorf("String(): got %s, want %s", s, want1)
	}

	want1 = "{*string, <-chan int}"
	want2 = "{<-chan int, *string}"
	if s := tmap.KeysString(); s != want1 && s != want2 {
		t.Errorf("KeysString(): got %s, want %s", s, want1)
	}

	// Keys().
	I := types.Identical
	switch k := tmap.Keys(); {
	case I(k[0], tChanInt1) && I(k[1], tPStr1): // ok
	case I(k[1], tChanInt1) && I(k[0], tPStr1): // ok
	default:
		t.Errorf("Keys(): got %v, want %s", k, want2)
	}

	if l := tmap.Len(); l != 2 {
		t.Errorf("Len(): got %d, want 1", l)
	}
	// At via original key.
	if v := tmap.At(tPStr1); v != "*string again" {
		t.Errorf("At(): got %q, want \"*string again\"", v)
	}
	hamming := 1
	tmap.Iterate(func(key types.Type, value any) {
		switch {
		case I(key, tChanInt1):
			hamming *= 2 // ok
		case I(key, tPStr1):
			hamming *= 3 // ok
		}
	})
	if hamming != 6 {
		t.Errorf("Iterate: hamming: got %d, want %d", hamming, 6)
	}

	if v := tmap.At(tChanInt2); v != "<-chan int" {
		t.Errorf("At(): got %q, want \"<-chan int\"", v)
	}
	// Deletion with key equal to present one.
	if !tmap.Delete(tChanInt2) {
		t.Errorf("Delete() of existing key: got false, want true")
	}

	// Now: {*string: "*string again"}

	if l := tmap.Len(); l != 1 {
		t.Errorf("Len(): got %d, want 1", l)
	}
	// Deletion again.
	if !tmap.Delete(tPStr2) {
		t.Errorf("Delete() of existing key: got false, want true")
	}

	// Now: {}

	if l := tmap.Len(); l != 0 {
		t.Errorf("Len(): got %d, want %d", l, 0)
	}
	if s := tmap.String(); s != "{}" {
		t.Errorf("Len(): got %q, want %q", s, "")
	}
}

func TestMapGenerics(t *testing.T) {
	const src = `
package p

// Basic defined types.
type T1 int
type T2 int

// Identical methods.
func (T1) M(int) {}
func (T2) M(int) {}

// A constraint interface.
type C interface {
	~int | string
}

type I interface {
}

// A generic type.
type G[P C] int

// Generic functions with identical signature.
func Fa1[P C](p P) {}
func Fa2[Q C](q Q) {}

// Fb1 and Fb2 are identical and should be mapped to the same entry, even if we
// map their arguments first.
func Fb1[P any](x *P) {
	var y *P // Map this first.
	_ = y
}
func Fb2[Q any](x *Q) {
}

// G1 and G2 are mutally recursive, and have identical methods.
type G1[P any] struct{
	Field *G2[P]
}
func (G1[P]) M(G1[P], G2[P]) {}
type G2[Q any] struct{
	Field *G1[Q]
}
func (G2[P]) M(G1[P], G2[P]) {}

// Method type expressions on different generic types are different.
var ME1 = G1[int].M
var ME2 = G2[int].M

// ME1Type should have identical type as ME1.
var ME1Type func(G1[int], G1[int], G2[int])

// Examples from issue #51314
type Constraint[T any] any
func Foo[T Constraint[T]]() {}
func Fn[T1 ~*T2, T2 ~*T1](t1 T1, t2 T2) {}

// Bar and Baz are identical to Foo.
func Bar[P Constraint[P]]() {}
func Baz[Q any]() {} // The underlying type of Constraint[P] is any.
// But Quux is not.
func Quux[Q interface{ quux() }]() {}


type Issue56048_I interface{ m() interface { Issue56048_I } }
var Issue56048 = Issue56048_I.m

type Issue56048_Ib interface{ m() chan []*interface { Issue56048_Ib } }
var Issue56048b = Issue56048_Ib.m

// Non-generic alias
type NonAlias int
type Alias1 = NonAlias
type Alias2 = NonAlias

// Generic alias (requires go1.23)
// type SetOfInt = map[int]bool
// type Set[T comparable] = map[K]bool
// type SetOfInt2 = Set[int]
`

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "p.go", src, 0)
	if err != nil {
		t.Fatal(err)
	}

	var conf types.Config
	pkg, err := conf.Check("", fset, []*ast.File{file}, nil)
	if err != nil {
		t.Fatal(err)
	}

	// Collect types.
	scope := pkg.Scope()
	var (
		T1      = scope.Lookup("T1").Type().(*types.Named)
		T2      = scope.Lookup("T2").Type().(*types.Named)
		T1M     = T1.Method(0).Type()
		T2M     = T2.Method(0).Type()
		G       = scope.Lookup("G").Type()
		GInt1   = instantiate(t, G, types.Typ[types.Int])
		GInt2   = instantiate(t, G, types.Typ[types.Int])
		GStr    = instantiate(t, G, types.Typ[types.String])
		C       = scope.Lookup("C").Type()
		CI      = C.Underlying().(*types.Interface)
		I       = scope.Lookup("I").Type()
		II      = I.Underlying().(*types.Interface)
		U       = CI.EmbeddedType(0).(*types.Union)
		Fa1     = scope.Lookup("Fa1").Type().(*types.Signature)
		Fa2     = scope.Lookup("Fa2").Type().(*types.Signature)
		Fa1P    = Fa1.TypeParams().At(0)
		Fa2Q    = Fa2.TypeParams().At(0)
		Fb1     = scope.Lookup("Fb1").Type().(*types.Signature)
		Fb1x    = Fb1.Params().At(0).Type()
		Fb1y    = scope.Lookup("Fb1").(*types.Func).Scope().Lookup("y").Type()
		Fb2     = scope.Lookup("Fb2").Type().(*types.Signature)
		Fb2x    = Fb2.Params().At(0).Type()
		G1      = scope.Lookup("G1").Type().(*types.Named)
		G1M     = G1.Method(0).Type()
		G1IntM1 = instantiate(t, G1, types.Typ[types.Int]).(*types.Named).Method(0).Type()
		G1IntM2 = instantiate(t, G1, types.Typ[types.Int]).(*types.Named).Method(0).Type()
		G1StrM  = instantiate(t, G1, types.Typ[types.String]).(*types.Named).Method(0).Type()
		G2      = scope.Lookup("G2").Type()
		// See below.
		// G2M     = G2.Method(0).Type()
		G2IntM  = instantiate(t, G2, types.Typ[types.Int]).(*types.Named).Method(0).Type()
		ME1     = scope.Lookup("ME1").Type()
		ME1Type = scope.Lookup("ME1Type").Type()
		ME2     = scope.Lookup("ME2").Type()

		Constraint  = scope.Lookup("Constraint").Type()
		Foo         = scope.Lookup("Foo").Type()
		Fn          = scope.Lookup("Fn").Type()
		Bar         = scope.Lookup("Foo").Type()
		Baz         = scope.Lookup("Foo").Type()
		Quux        = scope.Lookup("Quux").Type()
		Issue56048  = scope.Lookup("Issue56048").Type()
		Issue56048b = scope.Lookup("Issue56048b").Type()

		// In go1.23 these will be *types.Alias; for now they are all int.
		NonAlias = scope.Lookup("NonAlias").Type()
		Alias1   = scope.Lookup("Alias1").Type()
		Alias2   = scope.Lookup("Alias2").Type()

		// Requires go1.23.
		// SetOfInt    = scope.Lookup("SetOfInt").Type()
		// Set         = scope.Lookup("Set").Type().(*types.Alias)
		// SetOfInt2   = scope.Lookup("SetOfInt2").Type()
	)

	tmap := new(typeutil.Map)

	steps := []struct {
		typ      types.Type
		name     string
		newEntry bool
	}{
		{T1, "T1", true},
		{T2, "T2", true},
		{G, "G", true},
		{C, "C", true},
		{CI, "CI", true},
		{U, "U", true},
		{I, "I", true},
		{II, "II", true}, // should not be identical to CI

		// Methods can be identical, even with distinct receivers.
		{T1M, "T1M", true},
		{T2M, "T2M", false},

		// Identical instances should map to the same entry.
		{GInt1, "GInt1", true},
		{GInt2, "GInt2", false},
		// ..but instantiating with different arguments should yield a new entry.
		{GStr, "GStr", true},

		// F1 and F2 should have identical signatures.
		{Fa1, "F1", true},
		{Fa2, "F2", false},

		// The identity of P and Q should not have been affected by type parameter
		// masking during signature hashing.
		{Fa1P, "F1P", true},
		{Fa2Q, "F2Q", true},

		{Fb1y, "Fb1y", true},
		{Fb1x, "Fb1x", false},
		{Fb2x, "Fb2x", true},
		{Fb1, "Fb1", true},

		// Mapping elements of the function scope should not affect the identity of
		// Fb2 or Fb1.
		{Fb2, "Fb1", false},

		{G1, "G1", true},
		{G1M, "G1M", true},
		{G2, "G2", true},

		// See golang/go#49912: receiver type parameter names should be ignored
		// when comparing method identity.
		// {G2M, "G2M", false},
		{G1IntM1, "G1IntM1", true},
		{G1IntM2, "G1IntM2", false},
		{G1StrM, "G1StrM", true},
		{G2IntM, "G2IntM", false}, // identical to G1IntM1

		{ME1, "ME1", true},
		{ME1Type, "ME1Type", false},
		{ME2, "ME2", true},

		// See golang/go#51314: avoid infinite recursion on cyclic type constraints.
		{Constraint, "Constraint", true},
		{Foo, "Foo", true},
		{Fn, "Fn", true},
		{Bar, "Bar", false},
		{Baz, "Baz", false},
		{Quux, "Quux", true},

		{Issue56048, "Issue56048", true},   // (not actually about generics)
		{Issue56048b, "Issue56048b", true}, // (not actually about generics)

		// All three types are identical.
		{NonAlias, "NonAlias", true},
		{Alias1, "Alias1", false},
		{Alias2, "Alias2", false},

		// Generic aliases: requires go1.23.
		// {SetOfInt, "SetOfInt", true},
		// {Set, "Set", false},
		// {SetOfInt2, "SetOfInt2", false},
	}

	for _, step := range steps {
		existing := tmap.At(step.typ)
		if (existing == nil) != step.newEntry {
			t.Errorf("At(%s) = %v, want new entry: %t", step.name, existing, step.newEntry)
		}
		tmap.Set(step.typ, step.name)
	}
}

func instantiate(t *testing.T, origin types.Type, targs ...types.Type) types.Type {
	inst, err := types.Instantiate(nil, origin, targs, true)
	if err != nil {
		t.Fatal(err)
	}
	return inst
}

// ---------------------------------------------------------------------------
// TypeMap tests
// ---------------------------------------------------------------------------

func makeNamedType(pkgPath, pkgName, typeName string) *types.Named {
	pkg := types.NewPackage(pkgPath, pkgName)
	name := types.NewTypeName(0, pkg, typeName, nil)
	return types.NewNamed(name, types.Typ[types.Int], nil)
}

func TestTypeMapBasicOperations(t *testing.T) {
	m := &TypeMap{}

	// Len of empty map.
	if l := m.Len(); l != 0 {
		t.Fatalf("Len() on empty TypeMap: got %d, want 0", l)
	}

	// At on empty map.
	if v := m.At(tInt); v != nil {
		t.Fatalf("At() on empty TypeMap: got %v, want nil", v)
	}

	// Delete on empty map.
	if m.Delete(tInt) {
		t.Fatal("Delete() on empty TypeMap: got true, want false")
	}

	// Set and retrieve basic types.
	if prev := m.Set(tInt, "int_val"); prev != nil {
		t.Fatalf("Set() on empty TypeMap returned non-nil previous value: %v", prev)
	}
	if prev := m.Set(tStr, "str_val"); prev != nil {
		t.Fatalf("Set() on empty TypeMap returned non-nil previous value: %v", prev)
	}

	if l := m.Len(); l != 2 {
		t.Fatalf("Len(): got %d, want 2", l)
	}
	if v := m.At(tInt); v != "int_val" {
		t.Fatalf("At(int): got %v, want int_val", v)
	}
	if v := m.At(tStr); v != "str_val" {
		t.Fatalf("At(string): got %v, want str_val", v)
	}

	// Overwrite existing key.
	if prev := m.Set(tInt, "int_val2"); prev != "int_val" {
		t.Fatalf("Set() overwrite: got prev %v, want int_val", prev)
	}
	if v := m.At(tInt); v != "int_val2" {
		t.Fatalf("At(int) after overwrite: got %v, want int_val2", v)
	}
	if l := m.Len(); l != 2 {
		t.Fatalf("Len() after overwrite: got %d, want 2", l)
	}

	// Delete existing key.
	if !m.Delete(tInt) {
		t.Fatal("Delete(int): got false, want true")
	}
	if l := m.Len(); l != 1 {
		t.Fatalf("Len() after delete: got %d, want 1", l)
	}
	if v := m.At(tInt); v != nil {
		t.Fatalf("At(int) after delete: got %v, want nil", v)
	}

	// Delete already-deleted key.
	if m.Delete(tInt) {
		t.Fatal("Delete(int) second time: got true, want false")
	}

	// Test with named types that are structurally identical but distinct.
	namedA := makeNamedType("test/pkg", "pkg", "A")
	namedB := makeNamedType("test/pkg", "pkg", "B")

	m.Set(namedA, "A")
	m.Set(namedB, "B")
	if v := m.At(namedA); v != "A" {
		t.Fatalf("At(namedA): got %v, want A", v)
	}
	if v := m.At(namedB); v != "B" {
		t.Fatalf("At(namedB): got %v, want B", v)
	}

	// Test Keys.
	keys := m.Keys()
	if len(keys) != m.Len() {
		t.Fatalf("Keys() length %d != Len() %d", len(keys), m.Len())
	}

	// Test Iterate.
	count := 0
	m.Iterate(func(key types.Type, value any) {
		count++
	})
	if count != m.Len() {
		t.Fatalf("Iterate count %d != Len() %d", count, m.Len())
	}
}

func TestTypeMapLoadOrStore(t *testing.T) {
	m := &TypeMap{}

	// First call should store and return (value, false).
	val, loaded := m.LoadOrStore(tInt, "first")
	if loaded {
		t.Fatal("LoadOrStore first call: got loaded=true, want false")
	}
	if val != "first" {
		t.Fatalf("LoadOrStore first call: got val=%v, want first", val)
	}

	// Second call with same key should return (existing, true).
	val, loaded = m.LoadOrStore(tInt, "second")
	if !loaded {
		t.Fatal("LoadOrStore second call: got loaded=false, want true")
	}
	if val != "first" {
		t.Fatalf("LoadOrStore second call: got val=%v, want first", val)
	}

	// Verify Len is 1 (not 2).
	if l := m.Len(); l != 1 {
		t.Fatalf("Len() after two LoadOrStore: got %d, want 1", l)
	}

	// LoadOrStore with a different key should store.
	val, loaded = m.LoadOrStore(tStr, "string_val")
	if loaded {
		t.Fatal("LoadOrStore different key: got loaded=true, want false")
	}
	if val != "string_val" {
		t.Fatalf("LoadOrStore different key: got val=%v, want string_val", val)
	}
	if l := m.Len(); l != 2 {
		t.Fatalf("Len() after three LoadOrStore: got %d, want 2", l)
	}

	// Verify At returns the stored values.
	if v := m.At(tInt); v != "first" {
		t.Fatalf("At(int): got %v, want first", v)
	}
	if v := m.At(tStr); v != "string_val" {
		t.Fatalf("At(string): got %v, want string_val", v)
	}
}

func TestTypeMapSetNoLock(t *testing.T) {
	m := &TypeMap{}

	// SetNoLock on empty map.
	if prev := m.SetNoLock(tInt, "val1"); prev != nil {
		t.Fatalf("SetNoLock() on empty: got prev %v, want nil", prev)
	}
	if v := m.At(tInt); v != "val1" {
		t.Fatalf("At() after SetNoLock: got %v, want val1", v)
	}
	if l := m.Len(); l != 1 {
		t.Fatalf("Len() after SetNoLock: got %d, want 1", l)
	}

	// SetNoLock overwrite.
	if prev := m.SetNoLock(tInt, "val2"); prev != "val1" {
		t.Fatalf("SetNoLock() overwrite: got prev %v, want val1", prev)
	}
	if v := m.At(tInt); v != "val2" {
		t.Fatalf("At() after SetNoLock overwrite: got %v, want val2", v)
	}
	if l := m.Len(); l != 1 {
		t.Fatalf("Len() after SetNoLock overwrite: got %d, want 1", l)
	}

	// SetNoLock with different key.
	if prev := m.SetNoLock(tStr, "str"); prev != nil {
		t.Fatalf("SetNoLock() new key: got prev %v, want nil", prev)
	}
	if l := m.Len(); l != 2 {
		t.Fatalf("Len() after second SetNoLock: got %d, want 2", l)
	}
}

func TestTypeMapNilReceiver(t *testing.T) {
	var m *TypeMap

	// None of these should panic.
	if v := m.At(tInt); v != nil {
		t.Fatalf("At() on nil TypeMap: got %v, want nil", v)
	}
	if l := m.Len(); l != 0 {
		t.Fatalf("Len() on nil TypeMap: got %d, want 0", l)
	}
	if m.Delete(tInt) {
		t.Fatal("Delete() on nil TypeMap: got true, want false")
	}

	// Iterate on nil should be a no-op.
	m.Iterate(func(key types.Type, value any) {
		t.Fatal("Iterate on nil TypeMap should not call the function")
	})

	// Keys on nil should return empty slice.
	keys := m.Keys()
	if len(keys) != 0 {
		t.Fatalf("Keys() on nil TypeMap: got %d keys, want 0", len(keys))
	}

	// String on nil should return "{}".
	if s := m.String(); s != "{}" {
		t.Fatalf("String() on nil TypeMap: got %q, want %q", s, "{}")
	}
}

func TestTypeMapConcurrentSet(t *testing.T) {
	m := &TypeMap{}
	const numGoroutines = 50
	const typesPerGoroutine = 20

	// Pre-create all types so we can reuse the same pointers for verification.
	// Named types are compared by identity (pointer), not structure.
	allTypes := make([][]*types.Named, numGoroutines)
	for g := 0; g < numGoroutines; g++ {
		allTypes[g] = make([]*types.Named, typesPerGoroutine)
		for i := 0; i < typesPerGoroutine; i++ {
			allTypes[g][i] = makeNamedType(
				fmt.Sprintf("test/pkg%d", g),
				fmt.Sprintf("pkg%d", g),
				fmt.Sprintf("T%d", i),
			)
		}
	}

	var wg sync.WaitGroup
	wg.Add(numGoroutines)

	for g := 0; g < numGoroutines; g++ {
		g := g
		go func() {
			defer wg.Done()
			for i := 0; i < typesPerGoroutine; i++ {
				m.Set(allTypes[g][i], fmt.Sprintf("g%d_t%d", g, i))
			}
		}()
	}
	wg.Wait()

	// All entries should be present.
	expectedLen := numGoroutines * typesPerGoroutine
	if l := m.Len(); l != expectedLen {
		t.Fatalf("Len() after concurrent Set: got %d, want %d", l, expectedLen)
	}

	// Verify each entry is retrievable using the same type pointers.
	for g := 0; g < numGoroutines; g++ {
		for i := 0; i < typesPerGoroutine; i++ {
			v := m.At(allTypes[g][i])
			if v == nil {
				t.Fatalf("At(g%d_T%d) returned nil", g, i)
			}
			expected := fmt.Sprintf("g%d_t%d", g, i)
			if v != expected {
				t.Fatalf("At(g%d_T%d): got %v, want %v", g, i, v, expected)
			}
		}
	}
}

func TestTypeMapConcurrentLoadOrStore(t *testing.T) {
	m := &TypeMap{}
	const numGoroutines = 100

	// All goroutines race to LoadOrStore the same key.
	sharedType := makeNamedType("test/shared", "shared", "S")

	var wg sync.WaitGroup
	wg.Add(numGoroutines)

	storedCount := make(chan int, numGoroutines)
	loadedCount := make(chan int, numGoroutines)

	for g := 0; g < numGoroutines; g++ {
		g := g
		go func() {
			defer wg.Done()
			val, loaded := m.LoadOrStore(sharedType, g)
			if loaded {
				loadedCount <- val.(int)
			} else {
				storedCount <- val.(int)
			}
		}()
	}
	wg.Wait()
	close(storedCount)
	close(loadedCount)

	// Exactly one goroutine should have stored.
	stored := 0
	var winnerVal int
	for v := range storedCount {
		stored++
		winnerVal = v
	}
	if stored != 1 {
		t.Fatalf("Expected exactly 1 store, got %d", stored)
	}

	// All loaded goroutines should have received the winner's value.
	loaded := 0
	for v := range loadedCount {
		loaded++
		if v != winnerVal {
			t.Fatalf("Loaded value %d != stored value %d", v, winnerVal)
		}
	}

	if stored+loaded != numGoroutines {
		t.Fatalf("stored(%d) + loaded(%d) != %d", stored, loaded, numGoroutines)
	}

	// Map should have exactly 1 entry.
	if l := m.Len(); l != 1 {
		t.Fatalf("Len() after concurrent LoadOrStore: got %d, want 1", l)
	}
}

func TestTypeMapStringAndKeysString(t *testing.T) {
	m := &TypeMap{}
	m.Set(tStr, "hello")

	s := m.String()
	if s == "{}" {
		t.Fatal("String() should not be empty after Set")
	}
	if !strings.Contains(s, "string") {
		t.Fatalf("String() should contain 'string', got %q", s)
	}

	ks := m.KeysString()
	if ks == "{}" {
		t.Fatal("KeysString() should not be empty after Set")
	}
	if !strings.Contains(ks, "string") {
		t.Fatalf("KeysString() should contain 'string', got %q", ks)
	}
}

func TestTypeMapStringNil(t *testing.T) {
	var m *TypeMap
	s := m.toString(true)
	if s != "{}" {
		t.Fatalf("toString on nil map should return '{}', got %q", s)
	}
}

func TestTypeMapLoadOrStoreBasic(t *testing.T) {
	m := &TypeMap{}

	// First call should store
	val, loaded := m.LoadOrStore(tStr, "first")
	if loaded {
		t.Fatal("expected stored, not loaded")
	}
	if val != "first" {
		t.Fatalf("expected 'first', got %v", val)
	}

	// Second call should load existing
	val, loaded = m.LoadOrStore(tStr, "second")
	if !loaded {
		t.Fatal("expected loaded, not stored")
	}
	if val != "first" {
		t.Fatalf("expected 'first' (original), got %v", val)
	}

	if m.Len() != 1 {
		t.Fatalf("expected Len() == 1, got %d", m.Len())
	}
}

func TestTypeMapLoadOrStoreMultipleKeys(t *testing.T) {
	m := &TypeMap{}

	m.LoadOrStore(tStr, "s")
	m.LoadOrStore(tInt, "i")
	m.LoadOrStore(tPStr1, "p")

	if m.Len() != 3 {
		t.Fatalf("expected 3 entries, got %d", m.Len())
	}

	// Verify all values retrievable
	if v := m.At(tStr); v != "s" {
		t.Fatalf("expected 's', got %v", v)
	}
	if v := m.At(tInt); v != "i" {
		t.Fatalf("expected 'i', got %v", v)
	}
}

func TestTypeMapLoadOrStoreWriteLockPath(t *testing.T) {
	// Exercise the write-lock path: bucket exists but key is not present.
	m := &TypeMap{}

	// Store a key via Set to ensure the bucket exists.
	m.Set(tInt, "int_val")

	// LoadOrStore a different key — creates new entry via write-lock path.
	val, loaded := m.LoadOrStore(tPStr1, "pstr1_val")
	if loaded {
		t.Fatal("LoadOrStore should store new key, got loaded=true")
	}
	if val != "pstr1_val" {
		t.Fatalf("expected pstr1_val, got %v", val)
	}

	// LoadOrStore with tPStr2 (structurally identical to tPStr1).
	// Should find tPStr1's entry via the read-lock path.
	val, loaded = m.LoadOrStore(tPStr2, "pstr2_val")
	if !loaded {
		t.Fatal("LoadOrStore should load existing key, got loaded=false")
	}
	if val != "pstr1_val" {
		t.Fatalf("expected pstr1_val (original), got %v", val)
	}

	if m.Len() != 2 {
		t.Fatalf("expected 2 entries, got %d", m.Len())
	}
}

func TestTypeMapLoadOrStoreAfterDelete(t *testing.T) {
	// Exercise the hole-reuse path in LoadOrStore.
	m := &TypeMap{}

	m.Set(tInt, "int_val")
	m.Set(tStr, "str_val")

	// Delete one to create a hole.
	if !m.Delete(tStr) {
		t.Fatal("Delete should succeed")
	}
	if m.Len() != 1 {
		t.Fatalf("expected 1 after delete, got %d", m.Len())
	}

	// LoadOrStore with a new key.
	val, loaded := m.LoadOrStore(tChanInt1, "chan_val")
	if loaded {
		t.Fatal("LoadOrStore should store new key")
	}
	if val != "chan_val" {
		t.Fatalf("expected chan_val, got %v", val)
	}

	if v := m.At(tInt); v != "int_val" {
		t.Fatalf("At(int): got %v, want int_val", v)
	}
	if v := m.At(tChanInt1); v != "chan_val" {
		t.Fatalf("At(chan): got %v, want chan_val", v)
	}
}

func TestTypeMapLoadOrStoreDoubleCheck(t *testing.T) {
	// Exercise the double-check path: store via Set, then LoadOrStore with identical type.
	m := &TypeMap{}

	m.Set(tChanInt1, "chan_val")

	// tChanInt2 is identical to tChanInt1 but a different pointer.
	val, loaded := m.LoadOrStore(tChanInt2, "chan_val2")
	if !loaded {
		t.Fatal("LoadOrStore should find identical key")
	}
	if val != "chan_val" {
		t.Fatalf("expected chan_val, got %v", val)
	}
	if m.Len() != 1 {
		t.Fatalf("expected 1 entry, got %d", m.Len())
	}
}

func TestTypeMapConcurrentLoadOrStoreWriteLockDoubleCheck(t *testing.T) {
	// Exercise write-lock double-check path (lines 190-198 of pmap.go):
	// Bucket exists with a different entry, N goroutines race to LoadOrStore
	// the same NEW key. The first goroutine adds it under write-lock; the rest
	// discover it during the double-check after acquiring the write-lock.
	m := &TypeMap{}
	targetKey := makeNamedType("test/wldc", "wldc", "Target")
	h := hash(targetKey)

	// Seed the bucket at targetKey's hash with an unrelated entry so
	// tbl.Load(h) succeeds (fast path), but targetKey is not found under RLock.
	dummyKey := makeNamedType("test/wldc", "wldc", "Dummy")
	m.getTable().Store(h, &bucket{entries: []entry{{key: dummyKey, value: "dummy"}}})
	m.length.Add(1)

	const N = 100
	var wg sync.WaitGroup
	wg.Add(N)
	start := make(chan struct{})

	results := make([]struct {
		val    any
		loaded bool
	}, N)

	for i := 0; i < N; i++ {
		i := i
		go func() {
			defer wg.Done()
			<-start
			val, loaded := m.LoadOrStore(targetKey, i)
			results[i] = struct {
				val    any
				loaded bool
			}{val, loaded}
		}()
	}
	close(start)
	wg.Wait()

	storedCount := 0
	var storedVal int
	for i := 0; i < N; i++ {
		if !results[i].loaded {
			storedCount++
			storedVal = results[i].val.(int)
		}
	}
	if storedCount != 1 {
		t.Fatalf("expected exactly 1 store, got %d", storedCount)
	}
	for i := 0; i < N; i++ {
		if results[i].loaded && results[i].val.(int) != storedVal {
			t.Fatalf("goroutine %d loaded %d, want %d", i, results[i].val, storedVal)
		}
	}
	// 2 entries: dummy + target
	if l := m.Len(); l != 2 {
		t.Fatalf("Len() = %d, want 2", l)
	}
}

func TestTypeMapConcurrentLoadOrStoreHoleReuse(t *testing.T) {
	// Exercise write-lock hole-reuse path (lines 202-214 of pmap.go):
	// Bucket exists with a hole (nil-key entry from a prior delete), N goroutines
	// race to LoadOrStore a new key. The winner should reuse the hole.
	m := &TypeMap{}
	targetKey := makeNamedType("test/hole", "hole", "Target")
	h := hash(targetKey)

	// Seed bucket with two entries, then nil-out one to create a hole.
	keepKey := makeNamedType("test/hole", "hole", "Keep")
	holeKey := makeNamedType("test/hole", "hole", "Hole")
	b := &bucket{entries: []entry{
		{key: holeKey, value: "to_delete"},
		{key: keepKey, value: "keep"},
	}}
	m.getTable().Store(h, b)
	m.length.Add(2)

	// Create hole by nil-ing the first entry (simulates Delete).
	b.entries[0] = entry{}
	m.length.Add(-1)

	const N = 100
	var wg sync.WaitGroup
	wg.Add(N)
	start := make(chan struct{})

	results := make([]struct {
		val    any
		loaded bool
	}, N)

	for i := 0; i < N; i++ {
		i := i
		go func() {
			defer wg.Done()
			<-start
			val, loaded := m.LoadOrStore(targetKey, i)
			results[i] = struct {
				val    any
				loaded bool
			}{val, loaded}
		}()
	}
	close(start)
	wg.Wait()

	storedCount := 0
	for i := 0; i < N; i++ {
		if !results[i].loaded {
			storedCount++
		}
	}
	if storedCount != 1 {
		t.Fatalf("expected exactly 1 store, got %d", storedCount)
	}
	// 2 entries: keepKey + targetKey (hole was reused)
	if l := m.Len(); l != 2 {
		t.Fatalf("Len() = %d, want 2", l)
	}
}

func TestTypeMapConcurrentLoadOrStoreDifferentKeys(t *testing.T) {
	// Exercise slow path (lines 220-243 of pmap.go) and fast path concurrently
	// with many different keys. Some goroutines create new buckets (slow path),
	// others find existing buckets from natural hash collisions (fast path write-lock).
	m := &TypeMap{}
	const N = 200

	keys := make([]types.Type, N)
	for i := 0; i < N; i++ {
		keys[i] = makeNamedType("test/diff", "diff", fmt.Sprintf("T%d", i))
	}

	var wg sync.WaitGroup
	wg.Add(N)
	start := make(chan struct{})

	for i := 0; i < N; i++ {
		i := i
		go func() {
			defer wg.Done()
			<-start
			val, loaded := m.LoadOrStore(keys[i], i)
			if loaded {
				t.Errorf("goroutine %d: expected store, got load of %v", i, val)
			}
			if val != i {
				t.Errorf("goroutine %d: expected %d, got %v", i, i, val)
			}
		}()
	}
	close(start)
	wg.Wait()

	if l := m.Len(); l != N {
		t.Fatalf("Len() = %d, want %d", l, N)
	}
	for i := 0; i < N; i++ {
		v := m.At(keys[i])
		if v != i {
			t.Fatalf("At(T%d) = %v, want %d", i, v, i)
		}
	}
}

func TestTypeMapConcurrentLoadOrStoreSlowPathRace(t *testing.T) {
	// Exercise slow path bucket-creation race (lines 222-238 of pmap.go)
	// with keys guaranteed to share the same hash. Multiple goroutines race
	// to LoadOrStore different keys that map to the same bucket.
	m := &TypeMap{}

	// Create unique keys and find a set that share the same hash.
	type keyInfo struct {
		typ  types.Type
		hash uint32
	}
	hashGroups := make(map[uint32][]types.Type)
	for i := 0; i < 500; i++ {
		k := makeNamedType("test/spr", "spr", fmt.Sprintf("K%d", i))
		h := hash(k)
		hashGroups[h] = append(hashGroups[h], k)
	}

	// Find the largest collision group.
	var collisionKeys []types.Type
	for _, keys := range hashGroups {
		if len(keys) > len(collisionKeys) {
			collisionKeys = keys
		}
	}

	if len(collisionKeys) < 2 {
		t.Skip("no hash collisions found among 500 types — cannot exercise slow path race with different keys")
	}

	N := len(collisionKeys)
	var wg sync.WaitGroup
	wg.Add(N)
	start := make(chan struct{})

	for i := 0; i < N; i++ {
		i := i
		go func() {
			defer wg.Done()
			<-start
			val, loaded := m.LoadOrStore(collisionKeys[i], i)
			if loaded {
				t.Errorf("goroutine %d: expected store, got load of %v", i, val)
			}
			if val != i {
				t.Errorf("goroutine %d: expected %d, got %v", i, i, val)
			}
		}()
	}
	close(start)
	wg.Wait()

	if l := m.Len(); l != N {
		t.Fatalf("Len() = %d, want %d", l, N)
	}
	for i := 0; i < N; i++ {
		v := m.At(collisionKeys[i])
		if v != i {
			t.Fatalf("At(collisionKeys[%d]) = %v, want %d", i, v, i)
		}
	}
}

func TestTypeMapLoadOrStoreConcurrentBucketCreation(t *testing.T) {
	// Exercise the slow path where multiple goroutines race to create the same bucket.
	m := &TypeMap{}
	const numGoroutines = 50

	sharedType := makeNamedType("test/race", "race", "Shared")

	var wg sync.WaitGroup
	wg.Add(numGoroutines)

	results := make([]struct {
		val    any
		loaded bool
	}, numGoroutines)

	for g := 0; g < numGoroutines; g++ {
		g := g
		go func() {
			defer wg.Done()
			val, loaded := m.LoadOrStore(sharedType, g)
			results[g] = struct {
				val    any
				loaded bool
			}{val, loaded}
		}()
	}
	wg.Wait()

	storedCount := 0
	var storedVal int
	for g := 0; g < numGoroutines; g++ {
		if !results[g].loaded {
			storedCount++
			storedVal = results[g].val.(int)
		}
	}
	if storedCount != 1 {
		t.Fatalf("expected exactly 1 store, got %d", storedCount)
	}

	for g := 0; g < numGoroutines; g++ {
		if results[g].loaded && results[g].val.(int) != storedVal {
			t.Fatalf("loaded value %d != stored value %d", results[g].val, storedVal)
		}
	}

	if m.Len() != 1 {
		t.Fatalf("expected 1 entry, got %d", m.Len())
	}
}
